name: Feature request ✨
description: Suggest an idea or ask for a feature that you would like to have
labels: [feat-req]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for letting us know how we can improve our product! ☺️
  - type: textarea
    attributes:
      label: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What does the proposed solution look like?
    validations:
      required: true